# pull official base image
FROM python:3.8.16

# enable venv
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./app ./Backend/app
COPY ./requirements.txt ./Backend/
COPY ./.secret ./Backend/
WORKDIR /Backend

# Upgrade packages
RUN apt update && apt install -y \
    libpq-dev python3-dev && rm -rf /var/lib/apt/lists/*

# install requirements
RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 5050

# # start flask gunicorn
# ENTRYPOINT ["gunicorn", "-w 4","-b 0.0.0.0:5050", "main:app"]

# start FastAPI uvicorn
ENTRYPOINT ["python", "-m", "uvicorn", "--host", "0.0.0.0","--port", "5050", "app.main:app"]

